# Learning and practicing NumPy with examples and exercises

1. Examples: Numpy

In [1]:
import numpy as np
import matplotlib.pyplot as plt

1.1 Basic Indexing:

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


1.2 Slicing:


In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


1.3 Indexing 2D Arrays:

In [4]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(arr[1, 2])

6


1.4 Slicing 2D Arrays:

In [5]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(arr[:2, 1:])

[[2 3]
 [5 6]]


1.5 3D Tensor Indexing:

In [6]:
tensor = np.array([[[1 , 2 , 3 ], [4 , 5 , 6 ]],
                   [[7 , 8 , 9 ], [10, 11, 12]],
                   [[13, 14, 15], [16, 17, 18]]])
# Access specific elements
print(tensor[1, 0, 2])
# Access a slice of the tensor
print(tensor[1])

9
[[ 7  8  9]
 [10 11 12]]


1.6 Slicing a 3D Tensor:

In [ ]:
tensor = np.arange(27).reshape(3, 3, 3) 
# Slice along the first dimension
print(tensor[1])
# Slice along the second dimension
print(tensor[:, 1, :])
# Slice along the third dimension
print(tensor[:, :, 2])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]


1.7 4D Tensor Indexing:

In [11]:
tensor = np.arange(48).reshape(2, 3, 2, 4)
# Access a specific element
print(tensor[1, 2, 0, 3])
# Access a whole "block" (3D sub-tensor)
print(tensor[1, 2])

43
[[40 41 42 43]
 [44 45 46 47]]


1.8 Slicing a 4D Tensor:

In [12]:
tensor = np.arange(48).reshape(2, 3, 2, 4)
# Slice along the first dimension
print(tensor[1])
# Slice along the second dimension
print(tensor[:, 2, :, :])
# Slice along the third dimension
print(tensor[:, :, 0, :])

[[[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]]
[[[16 17 18 19]
  [20 21 22 23]]

 [[40 41 42 43]
  [44 45 46 47]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]
  [16 17 18 19]]

 [[24 25 26 27]
  [32 33 34 35]
  [40 41 42 43]]]


1.9 Matrix Addition:

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = A + B
print(result)

[[ 6  8]
 [10 12]]


1.10 Matrix Multiplication:

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


1.11 Transpose of a Matrix:

In [15]:
A = np.array([[1, 2], [3, 4]])
result = np.transpose(A)
print(result)

[[1 3]
 [2 4]]


1.12 Matrix Determinant and Inverse:

In [16]:
A = np.array([[1, 2], [3, 4]])
det = np.linalg.det(A)
inverse = np.linalg.inv(A)
print("Determinant:", det)
print("Inverse:\n", inverse)

Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


1.13 Eigenvalues and Eigenvectors:

In [17]:
A = np.array([[1, -1], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2.00000002 1.99999998]
Eigenvectors:
 [[-0.70710677 -0.70710679]
 [ 0.70710679  0.70710677]]


1.14 Solving Linear Equations:

In [18]:
A = np.array([[2, 1], [1, 1]])
b = np.array([3, 2])
solution = np.linalg.solve(A, b)
print("Solution:", solution)

Solution: [1. 1.]
